name: Go Backend CI
on:
  push:
    branches: ["main", "develop"]
    paths: ["QUICK-READ-BACKEND/**"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true
      - name: Build
        run: go build -v ./...
        working-directory: ./QUICK-READ-BACKEND
